//Sven.Week01.Methoden.Start();
//Sven.Week04.UserInputUebungen.Start();
//Sven.Week05.StringUebungen.Start();
//Sven.Week05.StringUebungen.Start();
//Sven.Week06.OOPList.List.Start();
//Sven.Week06.Person2.Person2Example.Start();
//Sven.Week06.KalenderUebungen.Start();
//Sven.Week06.OOPList.List.Start();
Sven.Week06.SelbstTest.SelbstTest.Start();