using David.Week06;
using David.Week06.OOP;
using David.Week06.Person2Main;
using David.Week06.ZOO;
using David.Week07;
//David.Week03.Week03Day02Arrays.Week03Day02();
//David.Week03.Week03Day03RandomArrays.StartWeek03Day03RandomArrays();
//David.Week03.Random2.Start();
//David.Week03.Try.StartTry();
//David.Week04.Day01.StartDay01();
//Gyula.Week04.MergeSortExample.Start();
//David.Week04.Day02.Start();
//David.Week04.Day02.Start();
//David.Week04.Day04.Start();
//David.Week04._D.Start2D();
//David.Week04.Array2D2.Start();
//David.Week04.arrayWE.Start();
//David.Week04.Day02CocktailShakerSort.Start();
//David.Week05.Strings.StartDay01();
//David.Week05.ReverseProgramm.StartReverseProgramm();
//David.Week05.Randomize.Start();
//David.Week05.ReverseProgramm.StartReverseProgramm();
//David.Week05.CountLetters.Start();
//David.Week05.ToDoListe.Start();
//David.Week05.Hesse.Start();
//David.Week05.count2.Start();
//David.Week05.Calendar.Start();
//David.Week05.Selftest.Start();
//David.Week06.PersonExample.PersonExample.Start();
//David.Week06.KurseTrainer.KurseUndTrainerExample.Start();
//List1.Start();
//Person2VOOP.Start();
//ZooMain.Start();
//BankProgram.Main();
//ObstKorbMain.Start();
David.Week07.ZooNew.ZooMain.Start();